/**
 * nearline-web — Single-file browser build
 *
 * High-performance near-duplicate string detection using MinHash + LSH.
 * This file is a self-contained version of @mattgrill/nearline-web with
 * @mattgrill/nearline-core inlined. No external dependencies required.
 *
 * Usage:
 *   import { findDuplicates, DuplicateFinder } from "./nearline-web";
 *
 *   const result = await findDuplicates(strings, { threshold: 0.8 });
 *   console.log(result.pairs);
 *
 * @license MIT
 * @see https://github.com/mattgrill/nearline
 */

// ── Types ────────────────────────────────────────────────────────────────────

export interface DuplicateFinderOptions {
  /** Jaccard similarity threshold (0-1). Default: 0.8 */
  threshold?: number;
  /** N-gram (shingle) size. Default: 3 */
  ngramSize?: number;
  /** Number of MinHash permutations (signature size). Default: 128 */
  numPermutations?: number;
  /** Number of LSH bands. Default: 32 */
  numBands?: number;
  /** Rows per LSH band. Default: 4 (numBands * bandSize should equal numPermutations) */
  bandSize?: number;
  /** Number of worker threads/workers. 0 = single-threaded, 'auto' = platform default. Default: 'auto' */
  workers?: number | "auto";
  /** Batch size for worker tasks. Default: 1000 */
  batchSize?: number;
  /** Optional preprocessing function applied to each string before shingling */
  preprocess?: (s: string) => string;
  /** Random seed for reproducible MinHash permutations. Default: 42 */
  seed?: number;
}

export interface DuplicatePair {
  /** Index of first string in the input array */
  indexA: number;
  /** Index of second string in the input array */
  indexB: number;
  /** Estimated Jaccard similarity (0-1) */
  similarity: number;
}

export interface DuplicateGroup {
  /** Indices of all strings in this duplicate group */
  indices: number[];
}

export interface FindDuplicatesResult {
  /** All duplicate pairs above the threshold */
  pairs: DuplicatePair[];
  /** Transitive duplicate groups */
  groups: DuplicateGroup[];
  /** Performance statistics */
  stats: FindDuplicatesStats;
}

export interface FindDuplicatesStats {
  /** Total time in milliseconds */
  totalTimeMs: number;
  /** Number of input strings */
  inputCount: number;
  /** Number of candidate pairs generated by LSH */
  candidateCount: number;
  /** Number of verified duplicate pairs */
  duplicateCount: number;
  /** Number of duplicate groups */
  groupCount: number;
}

interface ResolvedOptions {
  threshold: number;
  ngramSize: number;
  numPermutations: number;
  numBands: number;
  bandSize: number;
  workers: number;
  batchSize: number;
  preprocess: ((s: string) => string) | null;
  seed: number;
}

/** Browser-specific options extending the base options */
export interface ClientDuplicateFinderOptions extends DuplicateFinderOptions {
  /**
   * URL to the compiled Web Worker script.
   * Required for parallel computation in the browser.
   * If omitted, runs single-threaded.
   */
  workerUrl?: URL | string;
}

// ── FNV-1a Hashing ───────────────────────────────────────────────────────────

const FNV_OFFSET_BASIS = 0x811c9dc5;
const FNV_PRIME = 0x01000193;

/**
 * FNV-1a hash for a string.
 * Operates on charCode values directly (no encoding overhead).
 */
function fnv1aString(str: string, offset = 0, length = str.length): number {
  let hash = FNV_OFFSET_BASIS;
  const end = offset + length;
  for (let i = offset; i < end; i++) {
    hash ^= str.charCodeAt(i);
    hash = Math.imul(hash, FNV_PRIME);
  }
  return hash >>> 0;
}

/**
 * FNV-1a hash for a Uint32Array slice.
 * Used for LSH band hashing.
 */
function fnv1aUint32(arr: Uint32Array, offset: number, length: number): number {
  let hash = FNV_OFFSET_BASIS;
  const end = offset + length;
  for (let i = offset; i < end; i++) {
    const val = arr[i];
    hash ^= val & 0xff;
    hash = Math.imul(hash, FNV_PRIME);
    hash ^= (val >>> 8) & 0xff;
    hash = Math.imul(hash, FNV_PRIME);
    hash ^= (val >>> 16) & 0xff;
    hash = Math.imul(hash, FNV_PRIME);
    hash ^= (val >>> 24) & 0xff;
    hash = Math.imul(hash, FNV_PRIME);
  }
  return hash >>> 0;
}

// ── Shingling ────────────────────────────────────────────────────────────────

/**
 * Generate a set of n-gram hashes from a string.
 * Uses FNV-1a directly on character windows — no substring allocation.
 */
function shingle(str: string, ngramSize: number): Set<number> {
  const hashes = new Set<number>();
  const len = str.length;

  if (len < ngramSize) {
    if (len > 0) {
      hashes.add(fnv1aString(str, 0, len));
    }
    return hashes;
  }

  const count = len - ngramSize + 1;
  for (let i = 0; i < count; i++) {
    hashes.add(fnv1aString(str, i, ngramSize));
  }
  return hashes;
}

/**
 * Convert a shingle set to a Uint32Array for MinHash processing.
 */
function shingleToArray(shingles: Set<number>): Uint32Array {
  const arr = new Uint32Array(shingles.size);
  let idx = 0;
  for (const h of shingles) {
    arr[idx++] = h;
  }
  return arr;
}

// ── MinHash ──────────────────────────────────────────────────────────────────

function xorshift32(state: number): number {
  state ^= state << 13;
  state ^= state >>> 17;
  state ^= state << 5;
  return state >>> 0;
}

/**
 * Generate hash salts for MinHash permutations.
 */
function generateHashCoefficients(
  numPermutations: number,
  seed: number
): { hashA: Uint32Array; hashB: Uint32Array } {
  const hashA = new Uint32Array(numPermutations);
  const hashB = new Uint32Array(numPermutations);
  let state = seed === 0 ? 1 : seed;

  for (let i = 0; i < numPermutations; i++) {
    state = xorshift32(state);
    hashA[i] = state;
    state = xorshift32(state);
    hashB[i] = state;
  }

  return { hashA, hashB };
}

/**
 * Fast hash permutation using multiply-xorshift mixing.
 */
function permutedHash(val: number, a: number, b: number): number {
  let h = val;
  h = Math.imul(h ^ a, 0x85ebca6b);
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
  h = (h ^ b ^ (h >>> 16)) >>> 0;
  return h;
}

/**
 * Compute MinHash signature for a shingle set (Uint32Array of hashes).
 * Writes into the `signatures` buffer at the given offset.
 */
function computeSignature(
  shingles: Uint32Array,
  hashA: Uint32Array,
  hashB: Uint32Array,
  numPermutations: number,
  signatures: Uint32Array,
  sigOffset: number
): void {
  for (let p = 0; p < numPermutations; p++) {
    signatures[sigOffset + p] = 0xffffffff;
  }

  const shingleCount = shingles.length;
  if (shingleCount === 0) return;

  for (let s = 0; s < shingleCount; s++) {
    const val = shingles[s];
    for (let p = 0; p < numPermutations; p++) {
      const h = permutedHash(val, hashA[p], hashB[p]);
      if (h < signatures[sigOffset + p]) {
        signatures[sigOffset + p] = h;
      }
    }
  }
}

/**
 * Compute MinHash signatures for all strings.
 * Processes trigrams inline — no intermediate Set/Array allocation.
 */
function computeAllSignatures(
  strings: string[],
  ngramSize: number,
  numPermutations: number,
  hashA: Uint32Array,
  hashB: Uint32Array,
  preprocess: ((s: string) => string) | null
): Uint32Array {
  const n = strings.length;
  const signatures = new Uint32Array(n * numPermutations);

  for (let i = 0; i < n; i++) {
    const str = preprocess ? preprocess(strings[i]) : strings[i];
    computeSignatureFromString(
      str, ngramSize, hashA, hashB, numPermutations, signatures, i * numPermutations
    );
  }

  return signatures;
}

function computeSignatureFromString(
  str: string,
  ngramSize: number,
  hashA: Uint32Array,
  hashB: Uint32Array,
  numPermutations: number,
  signatures: Uint32Array,
  sigOffset: number
): void {
  for (let p = 0; p < numPermutations; p++) {
    signatures[sigOffset + p] = 0xffffffff;
  }

  const len = str.length;
  if (len === 0) return;

  if (len < ngramSize) {
    const val = fnv1aString(str, 0, len);
    for (let p = 0; p < numPermutations; p++) {
      signatures[sigOffset + p] = permutedHash(val, hashA[p], hashB[p]);
    }
    return;
  }

  const count = len - ngramSize + 1;
  for (let i = 0; i < count; i++) {
    const val = fnv1aString(str, i, ngramSize);
    for (let p = 0; p < numPermutations; p++) {
      const h = permutedHash(val, hashA[p], hashB[p]);
      if (h < signatures[sigOffset + p]) {
        signatures[sigOffset + p] = h;
      }
    }
  }
}

/**
 * Estimate Jaccard similarity between two strings from their MinHash signatures.
 */
function estimateSimilarity(
  signatures: Uint32Array,
  indexA: number,
  indexB: number,
  numPermutations: number
): number {
  const offsetA = indexA * numPermutations;
  const offsetB = indexB * numPermutations;
  let matches = 0;

  for (let p = 0; p < numPermutations; p++) {
    if (signatures[offsetA + p] === signatures[offsetB + p]) {
      matches++;
    }
  }

  return matches / numPermutations;
}

// ── LSH (Locality-Sensitive Hashing) ─────────────────────────────────────────

function encodePair(a: number, b: number, n: number): number {
  return a * n + b;
}

/**
 * Perform LSH banding to find candidate duplicate pairs.
 */
function findCandidates(
  signatures: Uint32Array,
  count: number,
  numPermutations: number,
  numBands: number,
  bandSize: number
): Set<number> {
  const candidates = new Set<number>();

  for (let band = 0; band < numBands; band++) {
    const bandOffset = band * bandSize;
    const buckets = new Map<number, number[]>();

    for (let i = 0; i < count; i++) {
      const sigOffset = i * numPermutations + bandOffset;
      const bucketKey = fnv1aUint32(signatures, sigOffset, bandSize);

      let bucket = buckets.get(bucketKey);
      if (!bucket) {
        bucket = [];
        buckets.set(bucketKey, bucket);
      }
      bucket.push(i);
    }

    for (const bucket of buckets.values()) {
      if (bucket.length < 2) continue;
      for (let i = 0; i < bucket.length; i++) {
        for (let j = i + 1; j < bucket.length; j++) {
          candidates.add(encodePair(bucket[i], bucket[j], count));
        }
      }
    }
  }

  return candidates;
}

/**
 * Decode an encoded pair value back to two indices.
 */
function decodePair(pair: number, count: number): [number, number] {
  const a = (pair / count) | 0;
  const b = pair % count;
  return [a, b];
}

// ── Union-Find ───────────────────────────────────────────────────────────────

/**
 * Union-Find (Disjoint Set Union) with path compression and union by rank.
 */
class UnionFind {
  private parent: Uint32Array;
  private rank: Uint8Array;

  constructor(size: number) {
    this.parent = new Uint32Array(size);
    this.rank = new Uint8Array(size);
    for (let i = 0; i < size; i++) {
      this.parent[i] = i;
    }
  }

  find(x: number): number {
    let root = x;
    while (this.parent[root] !== root) {
      root = this.parent[root];
    }
    while (this.parent[x] !== root) {
      const next = this.parent[x];
      this.parent[x] = root;
      x = next;
    }
    return root;
  }

  union(x: number, y: number): void {
    const rootX = this.find(x);
    const rootY = this.find(y);
    if (rootX === rootY) return;

    if (this.rank[rootX] < this.rank[rootY]) {
      this.parent[rootX] = rootY;
    } else if (this.rank[rootX] > this.rank[rootY]) {
      this.parent[rootY] = rootX;
    } else {
      this.parent[rootY] = rootX;
      this.rank[rootX]++;
    }
  }

  getGroups(indices: Set<number>): number[][] {
    const groups = new Map<number, number[]>();

    for (const idx of indices) {
      const root = this.find(idx);
      let group = groups.get(root);
      if (!group) {
        group = [];
        groups.set(root, group);
      }
      group.push(idx);
    }

    const result: number[][] = [];
    for (const group of groups.values()) {
      if (group.length > 1) {
        group.sort((a, b) => a - b);
        result.push(group);
      }
    }

    result.sort((a, b) => a[0] - b[0]);
    return result;
  }
}

// ── Pipeline ─────────────────────────────────────────────────────────────────

/** Signature for a parallel compute function */
type ParallelComputeFn = (
  strings: string[],
  ngramSize: number,
  numPermutations: number,
  hashA: Uint32Array,
  hashB: Uint32Array,
  numWorkers: number,
  batchSize: number
) => Promise<Uint32Array>;

/**
 * Resolve user options into fully-specified options.
 */
function resolveOptions(
  opts: DuplicateFinderOptions | undefined,
  defaultWorkers: number
): ResolvedOptions {
  let workers: number;
  if (opts?.workers === undefined || opts?.workers === "auto") {
    workers = defaultWorkers;
  } else {
    workers = opts.workers;
  }

  return {
    threshold: opts?.threshold ?? 0.8,
    ngramSize: opts?.ngramSize ?? 3,
    numPermutations: opts?.numPermutations ?? 128,
    numBands: opts?.numBands ?? 32,
    bandSize: opts?.bandSize ?? 4,
    workers,
    batchSize: opts?.batchSize ?? 1000,
    preprocess: opts?.preprocess ?? null,
    seed: opts?.seed ?? 42,
  };
}

const WORKER_THRESHOLD = 5000;

/**
 * Core pipeline: compute signatures, LSH, verify, group.
 */
async function executePipeline(
  strings: string[],
  options: ResolvedOptions,
  parallelCompute: ParallelComputeFn | null
): Promise<FindDuplicatesResult> {
  const startTime = performance.now();
  const n = strings.length;

  if (n < 2) {
    return {
      pairs: [],
      groups: [],
      stats: {
        totalTimeMs: performance.now() - startTime,
        inputCount: n,
        candidateCount: 0,
        duplicateCount: 0,
        groupCount: 0,
      },
    };
  }

  const { hashA, hashB } = generateHashCoefficients(
    options.numPermutations,
    options.seed
  );

  // Compute signatures
  let signatures: Uint32Array;
  const useWorkers = parallelCompute && options.workers > 0 && n >= WORKER_THRESHOLD;

  if (useWorkers) {
    signatures = await parallelCompute(
      strings,
      options.ngramSize,
      options.numPermutations,
      hashA,
      hashB,
      options.workers,
      options.batchSize
    );
  } else {
    signatures = computeAllSignatures(
      strings,
      options.ngramSize,
      options.numPermutations,
      hashA,
      hashB,
      options.preprocess
    );
  }

  // LSH candidate generation
  const candidateSet = findCandidates(
    signatures,
    n,
    options.numPermutations,
    options.numBands,
    options.bandSize
  );

  // Verify candidates
  const pairs: DuplicatePair[] = [];
  const uf = new UnionFind(n);
  const involvedIndices = new Set<number>();

  for (const pair of candidateSet) {
    const [a, b] = decodePair(pair, n);
    const sim = estimateSimilarity(signatures, a, b, options.numPermutations);
    if (sim >= options.threshold) {
      pairs.push({ indexA: a, indexB: b, similarity: sim });
      uf.union(a, b);
      involvedIndices.add(a);
      involvedIndices.add(b);
    }
  }

  pairs.sort((a, b) => b.similarity - a.similarity);

  const groupArrays = uf.getGroups(involvedIndices);
  const groups: DuplicateGroup[] = groupArrays.map((indices) => ({ indices }));

  return {
    pairs,
    groups,
    stats: {
      totalTimeMs: performance.now() - startTime,
      inputCount: n,
      candidateCount: candidateSet.size,
      duplicateCount: pairs.length,
      groupCount: groups.length,
    },
  };
}

/**
 * Build a query function against pre-computed signatures.
 */
function querySignatures(
  queryStr: string,
  options: ResolvedOptions,
  signatures: Uint32Array,
  hashA: Uint32Array,
  hashB: Uint32Array,
  corpusSize: number
): DuplicatePair[] {
  let processed = queryStr;
  if (options.preprocess) {
    processed = options.preprocess(processed);
  }

  const shingles = shingleToArray(shingle(processed, options.ngramSize));
  const querySig = new Uint32Array(options.numPermutations);
  computeSignature(shingles, hashA, hashB, options.numPermutations, querySig, 0);

  const matches: DuplicatePair[] = [];

  for (let i = 0; i < corpusSize; i++) {
    const offset = i * options.numPermutations;
    let matchCount = 0;
    for (let p = 0; p < options.numPermutations; p++) {
      if (querySig[p] === signatures[offset + p]) {
        matchCount++;
      }
    }
    const sim = matchCount / options.numPermutations;
    if (sim >= options.threshold) {
      matches.push({ indexA: -1, indexB: i, similarity: sim });
    }
  }

  matches.sort((a, b) => b.similarity - a.similarity);
  return matches;
}

// ── Web Worker Pool ──────────────────────────────────────────────────────────

interface WebWorkerPoolOptions {
  workerUrl?: URL | string;
}

/**
 * Create a parallel compute function using Web Workers.
 * Returns null if workerUrl is not provided.
 */
function createWebWorkerCompute(
  options: WebWorkerPoolOptions
): ParallelComputeFn | null {
  if (!options.workerUrl) return null;
  if (typeof Worker === "undefined") return null;

  const workerUrl = options.workerUrl;

  return async (
    strings: string[],
    ngramSize: number,
    numPermutations: number,
    hashA: Uint32Array,
    hashB: Uint32Array,
    numWorkers: number,
    batchSize: number
  ): Promise<Uint32Array> => {
    const n = strings.length;
    const signatures = new Uint32Array(n * numPermutations);

    // Create batches
    const batches: Array<{ start: number; end: number }> = [];
    for (let i = 0; i < n; i += batchSize) {
      batches.push({ start: i, end: Math.min(i + batchSize, n) });
    }

    const actualWorkers = Math.min(numWorkers, batches.length);
    let batchIndex = 0;

    const hashAArr = Array.from(hashA);
    const hashBArr = Array.from(hashB);

    const processBatch = (): Promise<void> => {
      return new Promise((resolve, reject) => {
        const processNext = (): void => {
          if (batchIndex >= batches.length) {
            resolve();
            return;
          }

          const batch = batches[batchIndex++];
          const batchStrings = strings.slice(batch.start, batch.end);

          const worker = new Worker(workerUrl, { type: "module" });

          worker.onmessage = (
            event: MessageEvent<{
              signatures: ArrayBuffer;
              startIndex: number;
              count: number;
            }>
          ) => {
            const resultSigs = new Uint32Array(event.data.signatures);
            const offset = event.data.startIndex * numPermutations;
            signatures.set(resultSigs, offset);
            worker.terminate();
            processNext();
          };

          worker.onerror = (err) => {
            worker.terminate();
            reject(new Error(err.message));
          };

          worker.postMessage({
            strings: batchStrings,
            startIndex: batch.start,
            ngramSize,
            numPermutations,
            hashA: hashAArr,
            hashB: hashBArr,
          });
        };

        processNext();
      });
    };

    const workerPromises: Promise<void>[] = [];
    for (let i = 0; i < actualWorkers; i++) {
      workerPromises.push(processBatch());
    }

    await Promise.all(workerPromises);
    return signatures;
  };
}

// ── Public API ───────────────────────────────────────────────────────────────

function getDefaultWorkers(): number {
  if (typeof navigator !== "undefined" && navigator.hardwareConcurrency) {
    return Math.max(1, navigator.hardwareConcurrency - 1);
  }
  return 1;
}

/**
 * Find near-duplicate strings in a dataset (browser-optimized).
 * Uses Web Workers for parallel computation when workerUrl is provided.
 */
export async function findDuplicates(
  strings: string[],
  opts?: ClientDuplicateFinderOptions
): Promise<FindDuplicatesResult> {
  const options = resolveOptions(opts, getDefaultWorkers());
  const parallelCompute = createWebWorkerCompute({
    workerUrl: opts?.workerUrl,
  });
  return executePipeline(strings, options, parallelCompute);
}

/**
 * Class API for incremental use and querying against a built index (browser-optimized).
 */
export class DuplicateFinder {
  private options: ResolvedOptions;
  private workerPoolOptions: WebWorkerPoolOptions;
  private strings: string[] = [];
  private signatures: Uint32Array | null = null;
  private hashA: Uint32Array;
  private hashB: Uint32Array;

  constructor(opts?: ClientDuplicateFinderOptions) {
    this.options = resolveOptions(opts, getDefaultWorkers());
    this.workerPoolOptions = { workerUrl: opts?.workerUrl };
    const { hashA, hashB } = generateHashCoefficients(
      this.options.numPermutations,
      this.options.seed
    );
    this.hashA = hashA;
    this.hashB = hashB;
  }

  addStrings(strings: string[]): void {
    this.strings.push(...strings);
    this.signatures = null;
  }

  async buildIndex(): Promise<void> {
    const parallelCompute = createWebWorkerCompute(this.workerPoolOptions);

    if (parallelCompute && this.options.workers > 0 && this.strings.length >= 5000) {
      this.signatures = await parallelCompute(
        this.strings,
        this.options.ngramSize,
        this.options.numPermutations,
        this.hashA,
        this.hashB,
        this.options.workers,
        this.options.batchSize
      );
    } else {
      this.signatures = computeAllSignatures(
        this.strings,
        this.options.ngramSize,
        this.options.numPermutations,
        this.hashA,
        this.hashB,
        this.options.preprocess
      );
    }
  }

  query(str: string): DuplicatePair[] {
    if (!this.signatures) {
      throw new Error("Index not built. Call buildIndex() first.");
    }
    return querySignatures(
      str,
      this.options,
      this.signatures,
      this.hashA,
      this.hashB,
      this.strings.length
    );
  }
}
