export interface DuplicateFinderOptions {
  /** Jaccard similarity threshold (0-1). Default: 0.8 */
  threshold?: number;
  /** N-gram (shingle) size. Default: 3 */
  ngramSize?: number;
  /** Number of MinHash permutations (signature size). Default: 128 */
  numPermutations?: number;
  /** Number of LSH bands. Default: 32 */
  numBands?: number;
  /** Rows per LSH band. Default: 4 (numBands * bandSize should equal numPermutations) */
  bandSize?: number;
  /** Number of worker threads/workers. 0 = single-threaded, 'auto' = platform default. Default: 'auto' */
  workers?: number | "auto";
  /** Batch size for worker tasks. Default: 1000 */
  batchSize?: number;
  /** Optional preprocessing function applied to each string before shingling */
  preprocess?: (s: string) => string;
  /** Random seed for reproducible MinHash permutations. Default: 42 */
  seed?: number;
}

export interface DuplicatePair {
  /** Index of first string in the input array */
  indexA: number;
  /** Index of second string in the input array */
  indexB: number;
  /** Estimated Jaccard similarity (0-1) */
  similarity: number;
}

export interface DuplicateGroup {
  /** Indices of all strings in this duplicate group */
  indices: number[];
}

export interface FindDuplicatesResult {
  /** All duplicate pairs above the threshold */
  pairs: DuplicatePair[];
  /** Transitive duplicate groups */
  groups: DuplicateGroup[];
  /** Performance statistics */
  stats: FindDuplicatesStats;
}

export interface FindDuplicatesStats {
  /** Total time in milliseconds */
  totalTimeMs: number;
  /** Number of input strings */
  inputCount: number;
  /** Number of candidate pairs generated by LSH */
  candidateCount: number;
  /** Number of verified duplicate pairs */
  duplicateCount: number;
  /** Number of duplicate groups */
  groupCount: number;
}

export interface ResolvedOptions {
  threshold: number;
  ngramSize: number;
  numPermutations: number;
  numBands: number;
  bandSize: number;
  workers: number;
  batchSize: number;
  preprocess: ((s: string) => string) | null;
  seed: number;
}
